services:
  app:
    container_name: lesta-start_tfidf-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "${PORT}"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    container_name: lesta-start_tfidf-db
    image: postgres:latest
    restart: always
    user: ${POSTGRES_USER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: lesta-start_tfidf-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/limits.conf:/etc/nginx/limits.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
